### ISSUE TITLE
Add information about the availability as flatpak package

### ISSUE THREAD

**Issue by newkit** [zealdocs/zealdocs.github.io#21]
Hey there, maybe it's a good idea to add information that zeal is also available through flatpak (and maybe other package universes) to the download page? Would have saved me some hassle of trying to self compile due to the lack of fedora packages. Oh, btw. the fedora packages are not available, the mentioned link https://apps.fedoraproject.org/packages/zeal does not work any longer apparently.

**Comment by trollixx** [comment]
Fixed by https://github.com/zealdocs/zealdocs.github.io/commit/ce6a10b84685991001e6362d8203c5455a24921d and https://github.com/zealdocs/zealdocs.github.io/commit/e4457ce347ca08f8e92e4ac324c9c9e198475b78.

**Comment by newkit** [comment]
Awesome, that was quick. Thank you so much! :-D
